# Generated by Django 2.1.3 on 2018-11-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioexample',
            name='summery',
            field=models.TextField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
