# Generated by Django 2.1.3 on 2018-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_portfolioexample_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioexample',
            name='summery',
            field=models.TextField(),
        ),
    ]
