# Generated by Django 2.1.3 on 2018-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181110_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioexample',
            name='link',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
