# Generated by Django 2.1.3 on 2018-11-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article_post',
            new_name='ArticlePost',
        ),
    ]
