# Generated by Django 2.1.3 on 2018-11-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181110_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='image_blog',
            field=models.ImageField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
