# Generated by Django 2.1.3 on 2018-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_image_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_summery',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
